package edu.utsa.cs3443.froggyfinance.controller;

import javafx.fxml.FXML;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

/**
 * CreditsController
 *
 * Handles user interactions on the Credits screen and provides navigation
 * back to the Main Menu. This controller is part of the FroggyFinance
 * application’s UI flow.
 *
 * @author Sofia Flores
 */
public class CreditsController {

    /**
     * Navigates back to the Main Menu screen.
     *
     * This method is triggered when the user clicks the "Back" button
     * on the Credits screen. It retrieves the current window (Stage)
     * from the event source and delegates scene switching to the
     * MainMenuController.
     *
     * @param event the action event generated by the button click
     */
    @FXML
    private void goBackToMainMenu(ActionEvent event) {
        Stage stage = (Stage) ((javafx.scene.Node) event.getSource()).getScene().getWindow();
        MainMenuController.show(stage);
    }
}
