package edu.utsa.cs3443.froggyfinance.controller;

import edu.utsa.cs3443.froggyfinance.BackgroundMusicPlayer;
import javafx.fxml.FXML;
import javafx.scene.control.Slider;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

/**
 * SettingsController
 *
 * Manages the Settings screen for the FroggyFinance application.
 * This controller handles the volume slider, allowing users to
 * adjust the background music volume in real time. It also handles
 * saving or cancelling changes and returning to the Main Menu.
 *
 * author: Sofia Flores
 */
public class SettingsController {

    /** Slider UI element for controlling background music volume. */
    @FXML
    private Slider volumeSlider;

    /**
     * Initializes the Settings screen.
     *
     * Sets the slider to the current volume level when the screen loads,
     * and adds a listener to update the volume in real time as the user
     * moves the slider.
     */
    @FXML
    public void initialize() {
        // Set initial slider value from current volume
        volumeSlider.setValue(BackgroundMusicPlayer.getVolume() * 100);

        // Update volume when slider moves
        volumeSlider.valueProperty().addListener((obs, oldVal, newVal) -> {
            float vol = newVal.floatValue() / 100f; // map 0-100 to 0-1
            BackgroundMusicPlayer.setVolume(vol);
        });
    }

    /**
     * Handles the Save button action.
     *
     * When the user clicks Save, any changes made are applied and
     * the application returns to the Main Menu.
     *
     * @param event the action event generated by clicking Save
     */
    @FXML
    private void handleSave(ActionEvent event) {
        switchToMainMenu(event);
    }

    /**
     * Handles the Cancel button action.
     *
     * When the user clicks Cancel, changes are discarded and the
     * application returns to the Main Menu.
     *
     * @param event the action event generated by clicking Cancel
     */
    @FXML
    private void handleCancel(ActionEvent event) {
        switchToMainMenu(event);
    }

    /**
     * Switches the view back to the Main Menu.
     *
     * This method is called by both Save and Cancel actions to
     * return the user to the Main Menu.
     *
     * @param event the action event triggering the switch
     */
    @FXML
    private void switchToMainMenu(ActionEvent event) {
        Stage stage = (Stage) volumeSlider.getScene().getWindow();
        MainMenuController.show(stage);
    }
}
